version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pastefy_app_1
      APP_PORT: 80

  db:
    image: mariadb:10.11@sha256:79cf033abf9089f27dd4c3e831cbef83048a52d6f52783930b647c56224d95c3
    user: "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: "tyooe"
      MYSQL_DATABASE: "pastefy"
      MYSQL_USER: "pastefy"
      MYSQL_PASSWORD: "tyooe"
    ports:
      - 3336:3306
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql:rw
    restart: on-failure

  app:
    image: interaapps/pastefy:6.7.5@sha256:cfa582e598cf00034de9431ce80cba75595d5a7016973e49f8108a90fe8bee76
    user: "1000:1000"
    environment:
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: "mysql"
      DATABASE_NAME: "pastefy"
      DATABASE_USER: "pastefy"
      DATABASE_PASSWORD: "tyooe"
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      SERVER_NAME: "http://umbrel-local:9900"
      # OAUTH2_PROVIDER_CLIENT_ID: 
      # OAUTH2_PROVIDER_CLIENT_SECRET: 
    restart: on-failure
    depends_on:
      - db
