version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lunalytics_web_1
      APP_PORT: 2308

  web:
    image: ksjaay/lunalytics:0.9.7@sha256:ff5550db6b19c763fbd3a89e122dd732fee68f75abf5f16671f08eb0847588e5
    user: "1000:1000"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 2308 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${APP_DATA_DIR}/data/lunalytics_data:/app/data:rw
      - ${APP_DATA_DIR}/data/logs:/app/logs:rw
