version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ashigaru_app_1
      APP_PORT: 7682

  app:
    image: ghcr.io/thenymman/ashi-t:1.0.0@sha256:8ca95054808eaf5e6e60cce8a4e3413e64a765ef4274c3f81c2b33f6e40bfc79
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/tor:/home/ashigaru/.ashigaru/tor
      - ${APP_DATA_DIR}/data/wallets:/home/ashigaru/.ashigaru/wallets
      - ${APP_DATA_DIR}/data/config:/home/ashigaru/.ashigaru
