version: '3'

services:
  baikal:
    image: ckulka/baikal:latest
    container_name: baikal
    ports:
      - "85:80"
    volumes:
      - ${APP_DATA_DIR}/data/baikal:/var/www/html/Specific
    environment:
      BAIKAL_DAV_REALM: "MyBaikalServer"

volumes:
  baikal-data:
