version: '3'

services:
  baikal:
    image: ckulka/baikal:latest@sha256:0e00560a698456e3b07a2cf41e176b5f5a10d1831eb15044c799b3f0d77de62c
    container_name: baikal
    ports:
      - "85:80"
    volumes:
      - ${APP_DATA_DIR}/data/baikal:/var/www/html/Specific
    environment:
      BAIKAL_DAV_REALM: "MyBaikalServer"

volumes:
  baikal-data:
