version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: yamtrack_web_1
      APP_PORT: 8000

  web:
    image: ghcr.io/fuzzygrim/yamtrack:0.24.6@sha256:7d837396c3dcdb67956aba9cd5fd767a9aa6f0cc97243be1189b8ea2a2ec1d8e
    # does not work yet rootless
    # user: "1000:1000"
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    depends_on:
      - redis
    environment:
        SECRET: ${APP_SEED}
        REDIS_URL: redis://yamtrack_redis_1:6379
    volumes:
      - ${APP_DATA_DIR}/data/db:/yamtrack/db:rw
      
  redis:
    image: redis:8.0.2@sha256:dbf3e4b6ad3ece9c733282ff3f16942ed754fdc4ea12332154f30a9a9b88c3af
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data:rw
