version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:11.1@sha256:5210b82e87653f3cb394ba7736b35ed10426894e8c678942b18e2047af6f4cdd
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://${DEVICE_DOMAIN_NAME}:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400

