version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:11.5@sha256:e3b1626d6026f1f714643ad9b0b14257b0ce9ab4cedb3a5e041eb540f2e12798
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://${DEVICE_DOMAIN_NAME}:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400


