version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: threema_web_1
      APP_PORT: 80

  web:
    image: dennysubke/threema-web:v2.6.1@sha256:963e3bf1268213308e5a1856a71306a9600a9f61faa04a4cbae2055be0318f8d
    restart: on-failure
