version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: homarr_web_1
      APP_PORT: 7575

  web:
    image: ghcr.io/homarr-labs/homarr:v1.30.0@sha256:6b686e5aa133a4a76d9a5558907b9be5f726b79e858750bf13dfe05e5380dc5a
    restart: on-failure
    environment:
      - SECRET_ENCRYPTION_KEY: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/appdata
      
