version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: kokoro_web_1
      APP_PORT: 8880

  web:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2@sha256:76549cce3c5cc5ed4089619a9cffc3d39a041476ff99c5138cd18b6da832c4d7
    restart: on-failure