version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: akaunting_app_1
      APP_PORT: 80

  app:
    image: akaunting/akaunting:3.1.19@sha256:2c2d922c5e2bacde8cfbd6261eaa178b65f5ad85b1c9f21907eabc5c8de1c28f
    restart: on-failure
    environment:
      AKAUNTING_SETUP: "true"
      LOCALE: en-US
      DB_HOST: denny-akaunting_db_1
      DB_PORT: 3306
      DB_NAME: akaunting
      DB_USERNAME: admin
      DB_PASSWORD: akaunting_password
      DB_PREFIX: asd_
      COMPANY_NAME: "My Company"
      COMPANY_EMAIL: my@company.com
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: umbrel
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: akaunting
      MYSQL_USER: admin
      MYSQL_PASSWORD: akaunting_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
