version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-excalidraw_app_1
      APP_PORT: 80 # Web client

  app:
    image: ghcr.io/ozencb/excalidraw-persist:1.0.3@sha256:c39c6027a6acea1fb9623eba3328d7ec0d821b957d4ba4d6800b1262e1346c67
    ports:
      - 4001:4000 # Server API
    restart: on-failure
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
