version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: excalidraw_web_1
      APP_PORT: 5000

  web:
    image: thisisbenny/excalidraw@sha256:66cd4512732ad249ad9173925dde74f46831ea46fcaeff10fb6da7c5125c8f49
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/excalidraw/data
    environment:
      - PUID=1000
      - PGID=1000

#https://github.com/excalidraw/excalidraw.git   
