version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: btctracker_web_1
      APP_PORT: 3000

  web:
    image: dennysubke/btc-tracker:v0.3.2@sha256:4b4492e9197717be3eac2dee64d31babf7739352820b61bec35c178765b7f0b9
    user: 1000:1000
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/src/data
