version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: btctracker_web_1
      APP_PORT: 3000

  web:
    image: thewilqq/btc-tracker:v0.6.2@sha256:a66e06f9b5c597c7ed893efab80917b8f5daca379cb7cd327363cd86c8773d4d
    restart: on-failure
    user: 1000:1000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3947
    volumes:
      - ${APP_DATA_DIR}/data:/app/data


