version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: btctracker_web_1
      APP_PORT: 3000

  web:
    image: thewilqq/btc-tracker:v0.6.2@sha256:04fa2d921d55514bc0e710e8be1a9e57371a4281d3eee09c2649a12a38acf446
    restart: on-failure
    user: 1000:1000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/bitcoin-tracker.db
      - NEXTAUTH_SECRET=${APP_SEED}
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:3947
    volumes:
      - ${APP_DATA_DIR}/data:/app/data



