version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: booklore_web_1
      APP_PORT: 6060
      
  web:
    image: booklore/booklore:v0.38.0@sha256:48d4cacd5961436a02b938dbb4f5b17bc4f9dd5ff3c8803170d268051088b9e4
    restart: on-failure
    environment:
      DATABASE_URL: jdbc:mariadb://db:3306/booklore
      DATABASE_USERNAME: bookloreuser
      DATABASE_PASSWORD: booklorepass
    depends_on:
      db:
        condition: service_started
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/app/data
      - ${APP_DATA_DIR}/data/books:/books

  db:
    image: mariadb:12.0.2@sha256:b30cc65b57a11a2e791ad5c06284e599fe9f1bf3fe9081a88d85bcf36389be4a
    restart: on-failure
    environment:
      MARIADB_DATABASE: booklore
      MARIADB_USER: bookloreuser
      MARIADB_PASSWORD: booklorepass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
