version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wizarr_app_1
      APP_PORT: 5690
      
  app:
    image: ghcr.io/wizarrrr/wizarr:v2025.10.4@sha256:15cfcd68d06f89a5fda198f2c0658f3c56ceb20d35cb78717a5fa54fb614dc12
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_BUILTIN_AUTH=false
      - TZ=Europe/Berlin